[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch",
]
build-backend = "setuptools.build_meta"


[project]
name = "cumesh"
version = "1.0+rocm10.0"
description = "Cuda mesh utils"
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jianfeng Xiang", email = "belljig@outlook.com" }
]
maintainers = [
    { name = "Drayton Monkman", email = "dmonkman@proton.me" }
]
dependencies = [
    "torch>=2.11.0",
    "tqdm",
]
